name: Release

on:
  push:
    tags:
      - "v*"

env:
  NODEVERSION: 17.x

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODEVERSION }}
          cache: "npm"
          registry-url: "https://registry.npmjs.org"
      - run: npm install
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTOMATION_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          registry-url: "https://npm.pkg.github.com"
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: softprops/action-gh-release@v1
